version: '3.7'

services:
  db:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres_data:/var/lib/pgsql/data
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./server:/code
      - /code/node_modules
    depends_on:
      - db
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - ./client:/code
    ports:
      - "8080:80"
    depends_on:
      - server

volumes:
  postgres_data:
